quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=18.1
# Off by default, any resources which require dev services must explicitly enable them
quarkus.datasource.devservices.enabled=false

# Currently an in memory implementation, should be swapped out for a real channel implementation when actually used
mp.messaging.outgoing.payment-processed.connector=smallrye-in-memory

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_JDBC_URL}

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.reuse=false

%test.quarkus.datasource.devservices.enabled=true